# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 12, 14, 42, 575372), editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 12, 14, 42, 575410), editable=False),
        ),
    ]
